クエリの最適化
penqe/nbdc-forked-togovar pull request #3
Opened 2022-06-13 07:35 UTC by neznayer

- debounce API のfetch
- automatic advanced search
- 新しいqueryが入ったら、実行中のfetchをキャンセルする

2022-06-13 14:16 UTC, penqe reviewed
2つほどコメントしました。
Prettier によるコード整形が入ると、レビューがけっこうしんどくなるので、コード整形は専用のブランチで一気にやった方が良いですね。。

2022-06-13 14:16 UTC, penqe commented on app/frontend/javascripts/classes/ConditionGroupView.js
> +  doneEditing() {
もしこの関数が、このクラス以外で呼ばれないのであれば（Privateであれば） `_doneEditing` にしてもらえますか。
あらかじめお伝えしてなくて申し訳ないですが、private property, private method には `_` を prefix にしています。

2022-06-13 14:16 UTC, penqe commented on app/frontend/javascripts/classes/ConditionGroupView.js
> +  doneEditing() {
ちなみに、ECMAScript の proposal では、
- private: `#`
- protected: `_`
という prefix になってて、`#` は多くのブラウザで実装済みだそうですが（letest の es では採用済み？）。

2022-06-13 14:16 UTC, penqe commented on app/frontend/javascripts/classes/ConditionGroupView.js
> +  doneEditing() {
なのでいずれ、`_`  は `#` に一括置換するかもです。

2022-06-13 14:16 UTC, penqe commented on app/frontend/javascripts/classes/StoreManager.js
> +import { mixin } from "./StoreManagerMixin.js";
single quote に変えていただきたいです。

2022-06-14 00:54 UTC, neznayer commented on app/frontend/javascripts/classes/ConditionGroupView.js
> +  doneEditing() {
@neznayer レビューありがとうございます。　`_` に修正します。

2022-06-14 20:35 UTC, penqe requested changes

2022-06-14 20:35 UTC, penqe commented on app/frontend/javascripts/classes/AdvancedSearchToolbar.js
> +    console.trace('canSearch');
@neznayer upstream の dev 環境にプルリク出したいので、log は削除してもらえますか

2022-06-14 20:35 UTC, penqe commented on app/frontend/javascripts/classes/StoreManager.js
> +import { mixin } from "./StoreManagerMixin.js";
このファイルは double quote に変換されているようです。

2022-06-15 09:54 UTC, neznayer commented on app/frontend/javascripts/classes/StoreManager.js
> +import { mixin } from "./StoreManagerMixin.js";
失礼しました 🙇

2022-06-16 23:12 UTC, penqe approved these changes
ありがとうございます

2022-06-17 01:10 UTC, closed without merging