Fix gene search function
penqe/nbdc-forked-togovar pull request #9
Opened 2022-10-05 10:26 UTC by YukikoNoda

gene検索に関して、検索ができるように修正しました。
現在エラーは出ていないと思うのですが、修正方法が合っているかわからないのでご確認をお願いいたします。

2022-10-05 10:49 UTC, penqe reviewed
ありがとうございます。
id にパラメータを渡しているようです。
`{"offset":0,"query":{"id":["BRAT1"]}}`
こうなるべきです。
`{"offset":0,"query":{"gene":[9999]}}`

2022-10-05 10:55 UTC, penqe commented
また、サジェスト用のAPIが誤ったままです。
正しいサジェスト用APIを呼ぶ修正は、かなり難しいのと、 @neznayer さんが疾患検索で同様の機能を作っているので、相談してみてください。

2022-10-12 01:36 UTC, YukikoNoda commented
**<現在までに完了していること>**
- gene検索のsuggestのAPIを変更し、候補が適切に表示されるようになりました
- suggestエリアのカーソルでの候補選択のエラーを解決しました
- placeholderを"BRCA2"に変更しました
- suggestエリアの上部に表示されていたDiseaseというtitleを`<h3>`ごと削除しました
※コードの理解を進めるために、関数の形を変更している箇所があります。
※一時的に使用が不明な箇所はコメントアウトをしています。


--------------------------------------------------
**<今後行う予定のもの>**
- placeholderの色を薄くする(薄いバージョンの変数を作成しようと考えています)
- APIから取得した`<em>`の斜体をnomalに、色を黄色にする(diseaseのSassを参考にする)
- Enterで表示されている候補を選択する
- aliasの記述をsimple searchを参考に実装する

2022-10-12 02:59 UTC, YukikoNoda commented
placeholderの色をほんの少しだけ薄くしました。
色はもともと`_variables.scss`に記載のあった`$COLOR_GRAY: #94928d;`を使用しています。
記述場所は、全てに反映させると考え、`_base.sass`に仮に記述しました。


<img width="396" alt="Screen Shot 2022-10-12 at 11 56 14" src="https://user-images.githubusercontent.com/47429234/195239303-4127ac85-e4ce-4455-a09a-bc9f8018e499.png">

2022-10-12 03:16 UTC, YukikoNoda commented
suggest一覧の斜体をnormalにし、記述に一致する箇所に色をつけました。
色は選択している色と同じで、`$COLOR_SELECTED: #FFDD00;`を使用しています。
他の色にしたほうがいいかもしれませんが、おすすめの色はありますでしょうか?
よろしくおねがいします。

<img width="121" alt="Screen Shot 2022-10-12 at 12 10 12" src="https://user-images.githubusercontent.com/47429234/195241334-a8fbff3f-079b-4439-b975-c286abf1ffc8.png">

2022-10-12 04:13 UTC, penqe commented
@YukikoNoda こんな感じはどうでしょう？
#ffff50
<img width="121" alt="195241334-a8fbff3f-079b-4439-b975-c286abf1ffc8" src="https://user-images.githubusercontent.com/5561434/195248296-dcd1b70d-c1ff-4c46-b3d3-4f699fa623ac.png">

2022-10-12 04:24 UTC, YukikoNoda commented
@penqe `_variables.scss`に`$COLOR_SUGGEST: #ffff50;`という変数名を使用し変更しました。

2022-10-13 02:38 UTC, YukikoNoda commented
aliasを表示しました。少し文が長いかもしれません。
<img width="309" alt="Screen Shot 2022-10-13 at 11 33 36" src="https://user-images.githubusercontent.com/47429234/195486061-af4725fa-7389-4f36-97c7-31c319de9440.png">

2022-10-13 03:16 UTC, YukikoNoda commented
Advanced search時の検索で、Enterで表示されている候補を選択できるように変更しました。

2022-10-14 08:05 UTC, YukikoNoda commented
以下2点を修正しました。
- aliasをクリックすると、検索条件に反映されないバグの修正。
- gene検索によりresultに反映されるようになりました。

ひとまずgeneに関するエラーは解決したかと思われます。

2022-10-17 02:05 UTC, neznayer commented on app/frontend/javascripts/classes/ConditionValueEditor.js
> +// import ConditionItemValueView from '../components/ConditionItemValueView';
もしインポートがいらないのであれば、この行を削除うをお願いいたします。

2022-10-17 02:10 UTC, neznayer commented on app/frontend/javascripts/classes/SearchFieldView.js
> +      // return false;
return false は必要でなければ、このコメントアウトされた行を削除うをお願いします。

2022-10-17 02:10 UTC, neznayer commented on app/frontend/javascripts/classes/SearchFieldView.js
> +    // e.preventDefault();
ここもです。

2022-10-17 02:12 UTC, neznayer commented on app/frontend/javascripts/classes/SearchFieldView.js
> +    // }
ここも、説明用のコメント以外は柵状しましう

2022-10-17 02:12 UTC, neznayer commented on app/frontend/javascripts/classes/SearchFieldView.js
> +        // if (this._suggestDictionaries.indexOf(key) !== -1) {
ここもです

2022-10-17 02:16 UTC, neznayer requested changes
ありがとうございます！ 👍 
基本的にいいだと思います！
変更していただきたいのは、いらないコメント行の削除ぐらいですね。

2022-10-24 07:43 UTC, penqe approved these changes
ありがとうございます！

2022-10-24 07:43 UTC, merged